// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAO4VbLsby0gJJqAG0xgJ-nzqAWqAkLk1k',
    appId: '1:633946865169:web:e31956a5354a65a2c8bbb0',
    messagingSenderId: '633946865169',
    projectId: 'cbmmg-f4bf2',
    authDomain: 'cbmmg-f4bf2.firebaseapp.com',
    storageBucket: 'cbmmg-f4bf2.firebasestorage.app',
    measurementId: 'G-H9JLNS2G6R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAW7bE5kfD519iDi_NW00ldJP1RIFsHt4g',
    appId: '1:633946865169:android:56aec0b080c8f58bc8bbb0',
    messagingSenderId: '633946865169',
    projectId: 'cbmmg-f4bf2',
    storageBucket: 'cbmmg-f4bf2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBmMsvcFuFLeUADDBioX9Pv-susW1qyFS8',
    appId: '1:633946865169:ios:cfacbcd358400974c8bbb0',
    messagingSenderId: '633946865169',
    projectId: 'cbmmg-f4bf2',
    storageBucket: 'cbmmg-f4bf2.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBmMsvcFuFLeUADDBioX9Pv-susW1qyFS8',
    appId: '1:633946865169:ios:cfacbcd358400974c8bbb0',
    messagingSenderId: '633946865169',
    projectId: 'cbmmg-f4bf2',
    storageBucket: 'cbmmg-f4bf2.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAO4VbLsby0gJJqAG0xgJ-nzqAWqAkLk1k',
    appId: '1:633946865169:web:da699bb08b351a9dc8bbb0',
    messagingSenderId: '633946865169',
    projectId: 'cbmmg-f4bf2',
    authDomain: 'cbmmg-f4bf2.firebaseapp.com',
    storageBucket: 'cbmmg-f4bf2.firebasestorage.app',
    measurementId: 'G-PSF1732J6K',
  );

}