name: "CD Prod"

on:
  push:
    branches:
      - main

jobs:
  android-deploy:
    name: Android Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.44.0'
          channel: 'stable'
          cache: true

      - name: Get dependencies
        run: flutter pub get

      - name: Generate key.properties
        run: |
          cd android
          touch key.properties
          echo "storePassword=${{ secrets.ANDROID_STORE_PASSWORD }}" >> key.properties
          echo "keyPassword=${{ secrets.ANDROID_KEY_PASSWORD }}" >> key.properties
          echo "keyAlias=bombeiro_app" >> key.properties
          echo "storeFile=./keystore.jks" >> key.properties

      - name: Decode keystore
        env:
          ANDROID_KEYSTORE: ${{ secrets.ANDROID_KEYSTORE }}
        run: |
          echo "$ANDROID_KEYSTORE" | base64 -d > ./android/app/keystore.jks

      - name: Build App Bundle
        run: flutter build appbundle --release

      - name: Setup Google Play credentials
        run: echo '${{ secrets.GOOGLE_PLAY_ACCESS_KEY_JSON }}' > service_account.json

      - name: Deploy bundle to Google Play
        uses: r0adkll/upload-google-play@v1.1.5
        with:
          serviceAccountJson: service_account.json
          packageName: br.com.bombeiro_app
          releaseFiles: build/app/outputs/bundle/release/app-release.aab
          tracks: internal
          status: completed