name: "CI-project" # Nome do workflow

on:
  pull_request:
    branches: main # Acionado em pull requests para a branch main

jobs:
  firebase-test-lab: # Nome do job
    name: Firebase Test Lab
    runs-on: ubuntu-latest
    steps:
      - name: Checkout no código
        uses: actions/checkout@v4

      - name: Configurar Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.44.0'
          channel: 'stable'
          cache: true

      - name: Flutter pub get
        run: flutter pub get

      - name: Build APKs for testing
        run: |
          pushd android
          flutter build apk --debug
          ./gradlew app:assembleAndroidTest
          ./gradlew app:assembleDebug -Ptarget=integration_test/app_test.dart
          popd

      - name: Setup gcloud CLI
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.FIREBASE_PROJECT_ID }}

      - name: Autenticar com o Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.FIREBASE_CREDENTIALS }}

      - name: Run Integration Test on Firebase Test Lab
        run: |
          gcloud firebase test android run --type instrumentation \
            --app build/app/outputs/apk/debug/app-debug.apk \
            --test build/app/outputs/apk/androidTest/debug/app-debug-androidTest.apk \
            --orientations=portrait \
            --use-orchestrator \
            --timeout 3m \
            --results-dir=tests/firebase