name: Flutter CI

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Baixar código
        uses: actions/checkout@v4

      - name: Configurar Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Instalar Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Baixar dependências
        run: flutter pub get

      - name: Rodar teste de integração
        run: flutter test integration_test -d windows