name: Flutter CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar código
        uses: actions/checkout@v4

      - name: Instalar Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Baixar dependências
        run: flutter pub get

      - name: Rodar teste de integração no Android
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 35
          arch: x86_64
          profile: pixel_6
          script: |
            flutter devices
            flutter test integration_test -d emulator-5554